# Use postgres/example user/password credentials
version: '3.9'

services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: abmin1234

    ports:
      - "5432:5432"
      
  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   container_name: pgadmin
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.compose
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     - postgres
  #   restart: unless-stopped
    
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
 